#mp3_board
set_property IOSTANDARD LVCMOS33 [get_ports o_XRST]
set_property IOSTANDARD LVCMOS33 [get_ports i_DREQ]
#set_property IOSTANDARD LVCMOS33 [get_ports i_SO]
set_property IOSTANDARD LVCMOS33 [get_ports o_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports o_SI]
set_property IOSTANDARD LVCMOS33 [get_ports o_XCS]
set_property IOSTANDARD LVCMOS33 [get_ports o_XDCS]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN G1 [get_ports i_DREQ]
#set_property PACKAGE_PIN F3 [get_ports i_SO]
set_property PACKAGE_PIN G4 [get_ports o_SCK]
set_property PACKAGE_PIN G2 [get_ports o_SI]
set_property PACKAGE_PIN H2 [get_ports o_XCS]
set_property PACKAGE_PIN H4 [get_ports o_XDCS]
set_property PACKAGE_PIN J15 [get_ports rst_n]
set_property PACKAGE_PIN H1 [get_ports o_XRST]


set_property IOSTANDARD LVCMOS33 [get_ports o_LED]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]


set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN J3 [get_ports rx]


#display 7
set_property IOSTANDARD LVCMOS33 [get_ports {odigit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {odigit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {odigit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {odigit[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {onum[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {onum[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {onum[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {onum[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {onum[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {onum[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {onum[0]}]

set_property PACKAGE_PIN T10 [get_ports {onum[0]}]
set_property PACKAGE_PIN R10 [get_ports {onum[1]}]
set_property PACKAGE_PIN K16 [get_ports {onum[2]}]
set_property PACKAGE_PIN K13 [get_ports {onum[3]}]
set_property PACKAGE_PIN P15 [get_ports {onum[4]}]
set_property PACKAGE_PIN T11 [get_ports {onum[5]}]
set_property PACKAGE_PIN L18 [get_ports {onum[6]}]

set_property PACKAGE_PIN J17 [get_ports {odigit[0]}]
set_property PACKAGE_PIN J18 [get_ports {odigit[1]}]
set_property PACKAGE_PIN T9 [get_ports {odigit[2]}]
set_property PACKAGE_PIN J14 [get_ports {odigit[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {odigit[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {odigit[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {odigit[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {odigit[4]}]
set_property PACKAGE_PIN P14 [get_ports {odigit[4]}]
set_property PACKAGE_PIN T14 [get_ports {odigit[5]}]
set_property PACKAGE_PIN K2 [get_ports {odigit[6]}]
set_property PACKAGE_PIN U13 [get_ports {odigit[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {o_led_song_select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led_song_select[0]}]
#vga
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]
set_property PACKAGE_PIN D8 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN B7 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN A3 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN B11 [get_ports VGA_HS]
set_property PACKAGE_PIN B12 [get_ports VGA_VS]

##Accelerometer

set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports ACL_MISO]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports ACL_MOSI]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports ACL_SCLK]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports ACL_CSN]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports ACL_INT1]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports ACL_INT2]

#others
set_property IOSTANDARD LVCMOS33 [get_ports o_next]

set_property PACKAGE_PIN V11 [get_ports {o_led_song_select[1]}]
set_property PACKAGE_PIN V12 [get_ports {o_led_song_select[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {o_vol_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vol_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vol_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vol_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vol_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vol_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vol_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vol_led[0]}]
set_property PACKAGE_PIN H17 [get_ports {o_vol_led[0]}]
set_property PACKAGE_PIN K15 [get_ports {o_vol_led[1]}]
set_property PACKAGE_PIN J13 [get_ports {o_vol_led[2]}]
set_property PACKAGE_PIN N14 [get_ports {o_vol_led[3]}]
set_property PACKAGE_PIN R18 [get_ports {o_vol_led[4]}]
set_property PACKAGE_PIN V17 [get_ports {o_vol_led[5]}]
set_property PACKAGE_PIN U17 [get_ports {o_vol_led[6]}]
set_property PACKAGE_PIN U16 [get_ports {o_vol_led[7]}]
set_property PACKAGE_PIN T15 [get_ports o_LED]
set_property PACKAGE_PIN U14 [get_ports o_next]


# set_property MARK_DEBUG true [get_nets {u_get_acl_data/x_data[3]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/x_data[6]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/x_data[7]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/y_data[4]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/y_data[7]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/x_data[1]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/y_data[5]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/y_data[6]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/x_data[2]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/x_data[4]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/x_data[0]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/x_data[5]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/y_data[0]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/y_data[1]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/y_data[2]}]
# set_property MARK_DEBUG true [get_nets {u_get_acl_data/y_data[3]}]
# #set_property MARK_DEBUG true [get_nets u_get_acl_data/ACL_CSN_OBUF]
# create_debug_core u_ila_0 ila
# set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
# set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
# set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
# set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
# set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
# set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
# set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
# set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
# set_property port_width 1 [get_debug_ports u_ila_0/clk]
# connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF]]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
# set_property port_width 8 [get_debug_ports u_ila_0/probe0]
# connect_debug_port u_ila_0/probe0 [get_nets [list {u_get_acl_data/y_data[0]} {u_get_acl_data/y_data[1]} {u_get_acl_data/y_data[2]} {u_get_acl_data/y_data[3]} {u_get_acl_data/y_data[4]} {u_get_acl_data/y_data[5]} {u_get_acl_data/y_data[6]} {u_get_acl_data/y_data[7]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
# set_property port_width 8 [get_debug_ports u_ila_0/probe1]
# connect_debug_port u_ila_0/probe1 [get_nets [list {u_get_acl_data/x_data[0]} {u_get_acl_data/x_data[1]} {u_get_acl_data/x_data[2]} {u_get_acl_data/x_data[3]} {u_get_acl_data/x_data[4]} {u_get_acl_data/x_data[5]} {u_get_acl_data/x_data[6]} {u_get_acl_data/x_data[7]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
# set_property port_width 1 [get_debug_ports u_ila_0/probe2]
# #connect_debug_port u_ila_0/probe2 [get_nets [list u_get_acl_data/ACL_CSN_OBUF]]
# set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
# set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
# set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
# connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]


set_property MARK_DEBUG true [get_nets u_get_acl_data_n_13]
set_property MARK_DEBUG true [get_nets u_get_acl_data_n_14]
set_property MARK_DEBUG true [get_nets u_get_acl_data_n_15]
set_property MARK_DEBUG true [get_nets u_get_acl_data_n_16]
set_property MARK_DEBUG true [get_nets u_get_acl_data_n_19]
set_property MARK_DEBUG true [get_nets u_get_acl_data_n_12]
set_property MARK_DEBUG true [get_nets u_get_acl_data_n_17]
set_property MARK_DEBUG true [get_nets u_get_acl_data_n_18]
set_property MARK_DEBUG true [get_nets {y_data[0]}]
set_property MARK_DEBUG true [get_nets {x_data[0]}]
set_property MARK_DEBUG true [get_nets {x_data[1]}]
set_property MARK_DEBUG true [get_nets {x_data[2]}]
set_property MARK_DEBUG true [get_nets {x_data[3]}]
set_property MARK_DEBUG true [get_nets {x_data[4]}]
set_property MARK_DEBUG true [get_nets {x_data[5]}]
set_property MARK_DEBUG true [get_nets {x_data[6]}]
set_property MARK_DEBUG true [get_nets {x_data[7]}]
set_property MARK_DEBUG true [get_nets ACL_MOSI_OBUF]
set_property MARK_DEBUG true [get_nets ACL_MISO_IBUF]
set_property MARK_DEBUG true [get_nets ACL_CSN_OBUF]
set_property MARK_DEBUG true [get_nets ACL_SCLK_OBUF]
set_property MARK_DEBUG true [get_nets rst_n_IBUF]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {y_data[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {x_data[0]} {x_data[1]} {x_data[2]} {x_data[3]} {x_data[4]} {x_data[5]} {x_data[6]} {x_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list ACL_CSN_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list ACL_MISO_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list ACL_MOSI_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list ACL_SCLK_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
